### ISSUE TITLE
Newlines in code blocks do not get formatted properly

### ISSUE THREAD

**Issue by RAnders00** [mmanela/MarkdownOutlook#19]
When I type:

``````
```java
public class Test
{
    public static void main(String[] args)
    {
        System.out.println("Hi.");
    }
}
```
``````

I expect every line of code to be on its own line - instead, all lines get condensed onto one line:

![screenshot](http://i.imgur.com/u8nmIiZ.png)

**Comment by leo102** [comment]
same issue observed...
