### ISSUE TITLE
[Ask for tips] Saving email as markdown

### ISSUE THREAD

**Issue by cavo789** [mmanela/MarkdownOutlook#25]
Hello Matthew,

I'm searching ... the exact opposite i.e. save an email as a markdown file; perhaps do you've any tips ?

I'm using a markdown based documentation software and would like to keep important mails (sent or received) into that software so I need to be able to select an email and save as a .md file.

Any tips are welcome ;-)

Thanks.

**Comment by michaeltansg** [comment]
Hi @cavo789,

Did you end up finding a solution for email to Markdown?

Cheers,
Michael
