### ISSUE TITLE
Markdown parser

### ISSUE THREAD

**Issue by Crissov** [mmanela/MarkdownOutlook#36]
You are currently linking to Google code for MarkdownSharp. It is available right here on Github: <https://github.com/StackExchange/MarkdownSharp>. 

However, its readme says, and rightly so, that all new projects should prefer an [implementation](https://github.com/commonmark/commonmark-spec/wiki/List-of-CommonMark-Implementations#c-1) that conforms to [Commonmark](https://commonmark.org), probably one that ships with some useful extensions (like tables and math or a code syntax highlighter). [Markdig](https://github.com/lunet-io/markdig) seems like the most sensible candidate for C#/.NET.

**Comment by mmanela** [comment]
The docs were wrong, we are using markdig already! (yay)
